import type { Metadata } from 'next'
import Header from './components/layout/Header'


 
// These styles apply to every route in the application
import './globals.css'
// import Hero from './components/widgets/Hero'
 

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
 
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* <Hero></Hero> */}
      <body>
        <Header/>

        {/* footer */}
        
        {children}</body>
    </html>
  )
}